### ISSUE TITLE
Loop error?

### ISSUE THREAD

**Issue by oakniiv** [zoome0215/predictBO#1]
![capture](https://user-images.githubusercontent.com/34109529/34839543-385a120a-f702-11e7-9ab5-71aa1d2e9a96.JPG)
\Local\Programs\Python\Python36-32\lib\imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 601, in _exec
  File "<frozen importlib._bootstrap>", line 148, in __enter__
  File "<frozen importlib._bootstrap>", line 166, in _get_module_lock
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by zoome0215** [comment]
30 seconds of googling the error message suggested me to try
```
import sys
sys.setrecursionlimit(10000)
```
change 10000 to whatever number that is suitable (preferentially less than 1,000,000).
This issue is python 3 specific. It shouldn't be occurring on python 2.7.
