### ISSUE TITLE
backtest.py doesn't work.

### ISSUE THREAD

**Issue by munkh-erdene** [zoome0215/predictBO#10]
Model is already saved but backtest.py doesn't work i got this error "NotFoundError (see above for traceback): Key Variable_36 not found in checkpoint"

NotFoundError (see above for traceback): Key Variable_36 not found in checkpoint
	 [[Node: save_4/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_4/Const_0_0, save_4/RestoreV2/tensor_names, save_4/RestoreV2/shape_and_slices)]]
	 [[Node: save_4/RestoreV2/_75 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_80_save_4/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by zoome0215** [comment]
Do you know which line in backtest.py giving this error?

**Comment by munkh-erdene** [comment]
It works after restart my computer. I was need reset tensorflow.
