### ISSUE TITLE
Live data

### ISSUE THREAD

**Issue by oakniiv** [zoome0215/predictBO#3]

**Comment by zoome0215** [comment]
It predicts in real time. `demotrade_tf.py` does it.

You must have AI from `tensorflow/make-AI.py` first. 

What `demotrade_tf.py` does is it takes the data from past 15 minutes with interval of two seconds (they can change if you want), and predict whether to predict if the best decision is to bet on  `Up`, `down` or `do nothing`. 

Real time values are Stored in the variable `val_list`, and prediction is done at `L176` of `demotrade_tf.py`

`pred_now = learner.select_action_norandom(input_now)`

Hope it helps!

**Comment by oakniiv** [comment]
I went through the code a little bit but I still see no source where the
original data comes from, where does he read it, source? And how does he
know if I want usd/jpy or eur/usd data.

**Comment by zoome0215** [comment]
To use other currencies you really need to learn how to use chromedriver. 

Ai is loaded at `L149`
`learner = learning_util.learn(AIname,0.001,possibleactions,weightactions,int(interval*60/periodint))`

It loads current `USD/JPY` exchange rate at `L169`
`currval = float(currvaltext.text)`

**Comment by oakniiv** [comment]
a

**Comment by zoome0215** [comment]
Well, my philosophy is that if we make everything public and people help each other for their benefits and the benefits of the each other, then world will be (may be a little bit but) a better place.

If they ban it, there are still many ways to make money and make people happy through learning how tensorflow works and what kind of things you can apply. You can totally do your thing without going public and make whatever money without telling me, but I will keep this public until I really endanger myself in anything related to this project if you know what I mean.

(and I also think that this is not a most efficient way to make money not everyone can understand what is going on the source code anyways, so don't really concerned about those things)

**Comment by oakniiv** [comment]
W

**Comment by zoome0215** [comment]
Trusy me, it's not as powerful as you think. I've written this in 7 days or so (of course little tweaks took a while though). It is and it should be something which everyone should be able to do and at least feel it. 

The version is pretty crap and it will take ages for this things to work out properly. It is good that you are interested in it, and start using `bash in windows` kind of tools which gets you out of this microsoft-owned  computing environment. It, I think is a good opportunity.

I know that everyone doesn't think and feel like I do, but at least I feel that way so I should act it, and same goes to you I think.

Well, I don't want to do a lot of political/ethical debates here, but it's good to listen to someone else's, like your self's, opinion. 

I do agree that heartless psychopaths are there to take advantage of everything out there. I think when something happens which puts me endanger is the time for me to make it private.

Now you sort of see a small portion of the vast and deep world of `free-and-open source`, I think you will, sometimes in the future, understand what really all of these are about.

**Comment by oakniiv** [comment]
C

**Comment by oakniiv** [comment]
A

**Comment by zoome0215** [comment]
Wow, I'm surprised that you are 18 and making an income from trading! I am really amazed!
 
I am 23, I'm doing a PhD with scholarship in UK. I learned this while completing my thesis so amount of time spent is not that much. I think like the younger mind of yourself can master it pretty quickly and surpasses me even more.

I know that it is a frustrating process that you have to do tons of things where if you have money you can do it bang and boom. I really do understand what you mean, and I do thought that way until few years ago; but more I learn and be familiar with the idea of this making things `open source` and make it available for `free` (look at this site, `Github` I'm using this for free instead of having everything locally, because they give me these spaces and environments because I'm open-saucing my project)!

I don't say it is a way of life or ideology, but certainly, it is sort of like growing this good vibe to other people who doesn't know about it.

**Comment by oakniiv** [comment]
I

**Comment by zoome0215** [comment]
That's exciting.

Well, you wrote
> I am afraid of is people abusing AI 
I think this is one of the reason people open-sourcing the things, to stop company black boxing the technology and to protect ourselves from abusers by creating something better with a cloud of knowledge.

anyways, I will be in UK for next few years. Hit me up if you are stuck on anything (life, programming, etc...). I will try my best to help the next generation.

I am working on a field called `quantum simulator`, which might be even more powerful by combining it with machine-learning. There are so many things ahead of you! Best wishes!

**Comment by oakniiv** [comment]
Thank you and good luck :)

**Comment by oakniiv** [comment]
One more thing, training the ai, saving it (ctrl+esc??) and then, how to
load it again and continue training? (edit: nevermind I need to install linux first and take it from there)
one question tho, is interface-less version doable? just the terminal
