### ISSUE TITLE
Period, time frame?

### ISSUE THREAD

**Issue by oakniiv** [zoome0215/predictBO#5]
interval = 15 # min  You mean the time frame which candles are showing?
betinterval = 45 # min Bet expiration?
periodint = 2 Tensorflow uses every 2 seconds to learn? 
wait = 5?

what do we need all of these for?
in binary you have expiration time and time frame which represents the candles, in this case the time frame is 2 seconds because that is data, so now, what do we need wait for, and interval for? all we need is expiration time that is counting down when the AI puts or calls. Can you please explain?

**Comment by zoome0215** [comment]
I am sorry, I've been very busy doing international flights.

`interval =15 #min`
is a window of time which AI takes the exchange rates. AI is not mighty. Input length must be consistent.
`betinterval = 5 `
is bet expiration
`periodint = 2` 
is with in the time specified with `interval`, AI takes in the data of every `periodint` seconds. Again, AI is not consistent. The shape of an input data must be consistent.

`wait = 5`
is waiting time which after one trade is placed to avoid putting multiple exchanges in small time intervals.

I will edit the comments when I have sufficient time.

**Comment by oakniiv** [comment]
Okay thanks I've been playing with the code for a while it has some potential but the whole point would be the AI deciding when to put or call not to have fixed time for making a bet I started making that now and I started doing a "predicter" for some other things too based on your code. Thanks ;)
