### ISSUE TITLE
the files already exist

### ISSUE THREAD

**Issue by atul2427** [zoome0215/predictBO#8]
the files already exist.. what is a error

**Comment by zoome0215** [comment]
Under what circumstances did you get this error?

**Comment by zoome0215** [comment]
you get this error when you run `truncatenight.py`
means you run this script more than twice, that truncated data already exist in the folder`
`/data/tickdata/truncateddata/`
if you want to remake all the truncated data files, you must delete all the contents in this folder.

**Comment by atul2427** [comment]
Ohkl but when I run tensorflow it couldn't work

**Comment by zoome0215** [comment]
what error messages do you get? I can't read your mind man...
