### ISSUE TITLE
About have to train 100,000 times.

### ISSUE THREAD

**Issue by munkh-erdene** [zoome0215/predictBO#9]
First of all thank you for sharing your code, its wonderful. Nepochs = 100000000 Are you seriously? Its takes long to train 20 epochs.

Can you explain about its taking huge time to train. I have a 1060 (6 GB) GPU but its taking a lot of time.

**Comment by zoome0215** [comment]
I set Nepoch = 100000000 so basically it can run forever. At the end of a year of training, the script saves the network. So you can test it any time.

**Comment by munkh-erdene** [comment]
Thank you for reply. What about 100,000 times? Is it same to "learned times" on printed text?

**Comment by zoome0215** [comment]
numepoch (epoch) and numlearns (learned times) are different.
1000 times or so will be enough I think.

**Comment by munkh-erdene** [comment]
Thank you.
